name: pasos_flutter
description: "Neo Led App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  intl: ^0.18.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/